# Generated by Django 4.2.1 on 2023-06-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.ManyToManyField(blank=True, default='good', to='yelp.tag'),
        ),
    ]
